// Generated by tools/stamp_version.py; do not edit by hand.
window.GAME_VERSION={
 "version": "1.24.0",
 "date": "2026-10-10",
 "build": "5ee2b4b",
 "season": "Glitched",
 "notes": [
  {
   "v": "1.24.0",
   "date": "2026-10-10",
   "title": "100 bots, 3x bigger blocks and bigger booster pads"
  },
  {
   "v": "1.23.0",
   "date": "2026-10-10",
   "title": "Start with the Mirror Fractal Guns and the Bouncer Ball"
  },
  {
   "v": "1.22.0",
   "date": "2026-10-10",
   "title": "Mirror Fractal Guns and the Bouncer Ball"
  },
  {
   "v": "1.21.0",
   "date": "2026-10-10",
   "title": "Vending machines, the RPG and the Grenade Launcher"
  },
  {
   "v": "1.20.0",
   "date": "2026-10-09",
   "title": "Grand deaths, a bigger box and 50 tougher bots"
  },
  {
   "v": "1.19.0",
   "date": "2026-10-09",
   "title": "Flying blocks, booster pads and infinite ammo"
  },
  {
   "v": "1.18.0",
   "date": "2026-10-08",
   "title": "The game is now called Inverted"
  },
  {
   "v": "1.17.0",
   "date": "2026-10-08",
   "title": "Zero-G only, now in TypeScript"
  },
  {
   "v": "1.16.0",
   "date": "2026-10-08",
   "title": "Cartoony Zero-G swimming and heal animations"
  },
  {
   "v": "1.15.0",
   "date": "2026-10-08",
   "title": "Hold guns up at the chest and carry the pickaxe in one hand"
  },
  {
   "v": "1.14.0",
   "date": "2026-10-07",
   "title": "Zero-G Box mode"
  },
  {
   "v": "1.13.0",
   "date": "2026-10-07",
   "title": "Homepage and UI glow-up, with a version badge"
  },
  {
   "v": "1.12.0",
   "date": "2026-10-07",
   "title": "Heroes & Villains skins: Kash's 10 picks"
  },
  {
   "v": "1.11.0",
   "date": "2026-10-06",
   "title": "Glitched look for the whole island, visible guns, unique sounds, gliders"
  },
  {
   "v": "1.10.0",
   "date": "2026-10-06",
   "title": "Glitched season, 16x island, bots always on hard"
  },
  {
   "v": "1.9.0",
   "date": "2026-10-06",
   "title": "Lock-in: auto swim, Fortnite pickaxe combo, bigger island with 100 players, crash impacts, 56 skins"
  },
  {
   "v": "1.8.0",
   "date": "2026-10-06",
   "title": "Realistic guns, two-handed pickaxe swing, and a better third-person view"
  },
  {
   "v": "1.7.0",
   "date": "2026-10-06",
   "title": "Equip pickaxes from the Locker, Fortnite-style swing and weak spots"
  },
  {
   "v": "1.6.0",
   "date": "2026-10-05",
   "title": "Add 100 themed pickaxes to the Armory in 3D"
  },
  {
   "v": "1.5.0",
   "date": "2026-10-05",
   "title": "Make every jump a somersault, even with a gun out"
  },
  {
   "v": "1.4.0",
   "date": "2026-10-05",
   "title": "Rework the drop, glider and swimming"
  },
  {
   "v": "1.3.0",
   "date": "2026-10-05",
   "title": "Upgrade character animation: flips, jumps, sprinting and swimming"
  },
  {
   "v": "1.2.0",
   "date": "2026-10-05",
   "title": "Rebuild the sound: layered guns, 3D audio, footsteps and ambience"
  },
  {
   "v": "1.1.0",
   "date": "2026-10-04",
   "title": "Replace the battle bus with an exploding private jet"
  }
 ]
};
