#!/usr/bin/env python3
"""Stamp version.js with the game's version and its "What's new" list.

Every merged pull request on main is one release: v1.<merged PR count>.0.
Run it on a branch before opening a PR, passing the new release's title,
and the version shown in the game will match once the PR merges:

    python3 tools/stamp_version.py --next "Homepage glow-up"
"""
import argparse, datetime, json, pathlib, re, subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent

def git(*args):
    return subprocess.run(['git', *args], cwd=ROOT, capture_output=True, text=True, check=True).stdout

def releases(base):
    out = []
    log = git('log', '--merges', '--first-parent', '--date=short', '--format=%h%x1f%ad%x1f%s%x1f%b%x1e', base)
    for rec in filter(str.strip, log.split('\x1e')):
        sha, date, subject, body = (rec.strip('\n').split('\x1f') + [''])[:4]
        m = re.match(r'Merge pull request #(\d+)', subject)
        if m:
            out.append({'pr': int(m.group(1)), 'date': date, 'sha': sha, 'title': body.strip().splitlines()[0] if body.strip() else subject})
    out.sort(key=lambda r: r['pr'])
    for i, r in enumerate(out, 1):
        r['v'] = f'1.{i}.0'
    return out

def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--next', help='title of the release this branch will become')
    ap.add_argument('--base', default='origin/main', help='branch whose merges count as releases')
    ap.add_argument('--season', default='Glitched')
    a = ap.parse_args()
    rel = releases(a.base)
    if a.next:
        rel.append({'pr': None, 'date': datetime.date.today().isoformat(), 'sha': git('rev-parse', '--short', 'HEAD').strip(), 'title': a.next, 'v': f'1.{len(rel) + 1}.0'})
    cur = rel[-1]
    data = {'version': cur['v'], 'date': cur['date'], 'build': cur['sha'], 'season': a.season,
            'notes': [{'v': r['v'], 'date': r['date'], 'title': r['title']} for r in reversed(rel)]}
    js = ('// Generated by tools/stamp_version.py; do not edit by hand.\n'
          'window.GAME_VERSION=' + json.dumps(data, indent=1, ensure_ascii=False) + ';\n')
    (ROOT / 'version.js').write_text(js, encoding='utf-8')
    print(f"version.js -> v{data['version']} ({len(rel)} releases)")

if __name__ == '__main__':
    main()
